namespace :job do
  desc "Delete the remnants generated by the annotation upload job"
  task clear: :environment do
    # Delete Job records
    Job.destroy_all

    # Delete uploaded files
    require 'fileutils'
    directory = "tmp/upload-*"
    list = Dir.glob Rails.root.join(directory)
    FileUtils.rm_rf(list)
  end
end
